<div class="d-flex align-items-center justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
        <p>
        Nos, itt van ez a kis csapat, a Safarcsik-Telegdi-Letső féle brancs. Jobbnál jobb vezetéknevek, mi? Már jó tíz éve foglalkozunk weblapok készítésével, tiszta profik vagyunk már a szakmában. Csupa elégedett ügyféllel büszkélkedhetünk meg minden, blablabla. Eddig azonban egy koszlott kis irodából csapattuk a dolgokat, mint valami magánnyomozó irodája a múlt század elejéről. Na jó, a munkavégzés továbbra is ebben a retro irodában fog zajlani, a dokumentumokat és az ügyintézést azonban átköltöztettük online térbe, ezt bogarászod most te is. Fasza lett, mi?
        </p><p>
        Most fel kéne sorolni egy csomó unalmas adatot a lényegesebb mérföldkövekről, a csapat tagjairól, a küzdelmes kezdeti időkről, a kitartó munka sikerrel való megkoronázásáról, az elégedett kuncsaftok számával egyenes arányban növekvő köbcentikről a szolgálati járgányaink tekintetében, stb. De ezekhez most nincs kedvem. Helyette bemásolok ide néhány random, nem jogdíjas passzust, csak hogy növekedjen a tartalom, tudod. Na, jó olvasgatást!
        </p><p>
        Ezékiel 25:17: Az igaz ember járta ösvényt mindkét oldalról szegélyezi az önző emberek igazságtalansága, és a gonoszok zsarnoksága. Áldott legyen az, ki az irgalmasság és jóakarat nevében átvezeti a gyöngéket a sötétség völgyén, mert ő valóban testvérének őrizője, és az elveszett gyermekek meglelője. Én pedig lesújtok majd tereád hatalmas bosszúval és rettentő haraggal, és amazokra is akik testvéreim ármányos elpusztítására törnek, és majd megtudjátok, hogy az én nevem az Úr, amikor szörnyű bosszúm lesújt reátok.
        </p><p>
        Dick hazafelé sétált az ócska, régi járdán, amelynek kockakövei között már burjánzott a fű. Az utcaseprők jó ideje nem jártak erre, így szemét is rengeteg volt. Ha nagy ritkán mégis erre ette őket a fene, akkor sem sokat törődtek a munkájuk végzésével. Inkább csak lődörögtek és beszélgettek (nem volt ritka eset, hogy ők maguk termelték a szemetet). Ez volt a város szegénynegyede, ahová Dick két hónapja költözött a lányával, Nellyvel. Egy sokkal nagyobb és jobb állapotban lévő házból költöztek ide, de Dicket ez nem zavarta, mert itt legalább nem kellett félve átlépnie a küszöböt, hogy vajon nem fog-e egy újabb este veszekedéssel, netán verekedéssel eltelni. Ugyanis az előző házban egy harmadik személlyel éltek együtt, akinek Dick négy évvel ezelőtt gyűrűt húzott az ujjára. Most is erre a Jane nevezetű hölgyre gondolt, miközben jobb kezével megdörgölte a bal karját, ahol az exneje két hónappal ezelőtt megszúrta egy dugóhúzóval. Még most is viselt egy kötést az ing alatt.
        </p><p>
        Dick szétnézett az úton, mielőtt átment volna a zebrán, bár nem volt rá különösebben szükség, mert ritkán járt erre autó. Errefelé nem tellett rá az embereknek, többnyire alkalmi munkákból tengődtek. Jobbik esetben. Mert hát a legtöbben, mondjuk ki nyíltan, lopással és kurválkodással keresték meg a csekélyke pénzüket. Ahogy Dick behúzott nyakkal baktatott a házuk felé, három nigger mellett ment el, akik nem tudták megállni, hogy belekössenek. Egyikük még meg is lökte, de Dick rájuk sem nézett, csak felgyorsította lépteit és reménykedett, hogy ennyivel megússza. Ő már csak ilyen gyámoltalan volt (persze jobban belegondolva talán jól tette, hogy nem állt le három boxossal verekedni). Ha nem lett volna ilyen félénk, talán kézben tudta volna tartani a feleségével kapcsolatos indulatokat.
        </p><p>
        Ez az egész történet hétköznapian indult, de a végére nagyon eldurvultak az események. A cingár alkatú Dick az egyetem befejezése után megismerkedett élete szerelmével, azzal a bizonyos Jane-nel. Nagyon jól elvoltak egymással, hamar házasság is lett a dologból. És mivel Jane nem csak testben, de határozottságban is felülmúlta őt, rögtön kialakultak az erőviszonyok: Dick papucs lett és mindenben kiszolgálta Jane-t. Ő járt el egyedül dolgozni, és az apjának a segítségével vett maguknak egy gyönyörű, kétszintes házat a családi negyedben. A törlesztőrészletekkel nem volt gond, ugyanis Dick nagyon jól kereső állást talált magának a jogász diplomájával. Eddig minden adott egy boldog családi történet kialakulásához. De volt egy kis bökkenő.
        </p><p>
        Már a kezdeti időkben is eljárt néha Jane keze, ha Dick véletlenül feltett ostoba kérdése rossz hangulatban találta őt. Ezek a pofonok persze sértették Dick önérzetét és saját férfiasságáról alkotott képét, de nem mert ellenkezni a feleségével. Ilyenkor inkább sértődötten elment hazulról, ám rövidesen vissza is ment és ő kért bocsánatot, amiért felbosszantotta imádottját. Többnyire ki is békültek, és az ágyban szentesítették ezt a békét. Ezek a korai dührohamok persze nem voltak komolyak, de azért visszanézve lehet, hogy már előrevetítették a későbbi szomorú eseményeket.
        </p>
    </div>
</div>

